[workspace]
resolver = "2"
members = ["io-trait", "io-impl", "io-test"]

[workspace.package]
authors = ["Sergey Shandar"]
license = "MIT"
repository = "https://github.com/datablockset/io"

[workspace.dependencies]
libc = "0.2.149"
